namespace: arbiza

name: firewall

version: 1.0.0

readme: README.md

authors:
  - Lucas Arbiza <@arbiza>

description: Deploys a firewall for Linux servers exposed to the Internet

license:
  - GPL-2.0-or-later

license_file: ""

tags:
  - firewall
  - iptables
  - linux

dependencies: {}

repository: https://github.com/arbiza/firewall

documentation: https://github.com/arbiza/firewall/blob/main/README.md

homepage: https://github.com/arbiza/firewall

issues: https://github.com/arbiza/firewall/issues

build_ignore: ["ansible.cfg"]
