---

- name: Playbook of arbiza.firewall
  hosts: "{{ target }}"
  become: true

  tasks:
    - ansible.builtin.import_role:
        name: arbiza.firewall.iptables
      vars:
        input:
          - source: any
            port: https
          - source: any
            port: https
        output:
          - destination: any
            port: https
        port_knocking:
          target: ssh
          knock:
            - 26896 
            - 4099 
            - 63793


    - name: Blue test
      tags: [blue, test]
      block:

        - name: Set var vlans
          ansible.builtin.set_fact:
            my_color_choice: 'blue'

        - name: Test blue
          ansible.builtin.assert:
            that: my_color_choice is arbiza.firewall.blue
