---

# When running this playbook for the first time, run with '--skip-tags knock'

- name: Port Knocking
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Knock, knock, knock
      arbiza.firewall.knock:
        knock_at:
          - host: "{{ hostvars['container_1'].ansible_host }}"
            ports: "{{ hostvars['container_1'].knocking_list[0].ports }}"
          - host: "{{ hostvars['container_2'].ansible_host }}"
            ports: "{{ hostvars['container_2'].knocking_list[0].ports }}"
        timeout: 2 # can be omitted; default is 10s
      delegate_to: localhost
      become: false
      register: knock_output
      tags: knock
    
    - debug:
        var: knock_output
      tags: knock


- name: Playbook of arbiza.firewall
  hosts: [container_1 container_2]
  become: true

  roles:
    - role: arbiza.firewall.iptables
      vars:
        input:
          - ports: https
            protocol: tcp
          - ports: http
            protocol: tcp
        output:
          - ports: https
            protocol: tcp
          - ports: http
            protocol: tcp
        port_knocking: "{{ knocking_list }}"
