---
- name: Port and protocol
  when: item.ports is defined
  block:
    - name: Allow INPUT traffic to port(s) {{ item.ports }}
      ansible.builtin.iptables:
        chain: INPUT
        protocol: "{{ item.protocol }}"
        destination_port: "{{ item.ports }}"
        ctstate: NEW
        syn: match
        jump: ACCEPT
        ip_version: "{{ ipvx }}"
      loop: "{{ ip }}"
      loop_control:
        loop_var: ipvx
      when: item.src is not defined

    - name: Allow INPUT traffic to port(s) {{ item.ports }} from {{ item.src }}
      ansible.builtin.iptables:
        chain: INPUT
        protocol: "{{ item.protocol }}"
        destination_port: "{{ item.ports }}"
        ctstate: NEW
        syn: match
        source: "{{ item.src }}"
        jump: ACCEPT
        ip_version: ipv4
      when: item.src is arbiza.firewall.ipv4_address or item.src is arbiza.firewall.ipv4_network

    - name: Allow INPUT traffic to port(s) {{ item.ports }} from {{ item.src }}
      ansible.builtin.iptables:
        chain: INPUT
        protocol: "{{ item.protocol }}"
        destination_port: "{{ item.ports }}"
        ctstate: NEW
        syn: match
        source: "{{ item.src }}"
        jump: ACCEPT
        ip_version: ipv6
      when: item.src is arbiza.firewall.ipv6_address or item.src is arbiza.firewall.ipv6_network

- name: Protocol only
  when: item.ports is not defined
  block:
    - name: Allow INPUT traffic to port(s) {{ item.ports }}
      ansible.builtin.iptables:
        chain: INPUT
        protocol: "{{ item.protocol }}"
        ctstate: NEW
        jump: ACCEPT
        ip_version: "{{ ipvx }}"
      loop: "{{ ip }}"
      loop_control:
        loop_var: ipvx
      when: item.src is not defined

    - name: Allow INPUT traffic to port(s) {{ item.ports }} from {{ item.src }}
      ansible.builtin.iptables:
        chain: INPUT
        protocol: "{{ item.protocol }}"
        ctstate: NEW
        source: "{{ item.src }}"
        jump: ACCEPT
        ip_version: ipv4
      when: item.src is arbiza.firewall.ipv4_address or item.src is arbiza.firewall.ipv4_network

    - name: Allow INPUT traffic to port(s) {{ item.ports }} from {{ item.src }}
      ansible.builtin.iptables:
        chain: INPUT
        protocol: "{{ item.protocol }}"
        ctstate: NEW
        source: "{{ item.src }}"
        jump: ACCEPT
        ip_version: ipv6
      when: item.src is arbiza.firewall.ipv6_address or item.src is arbiza.firewall.ipv6_network
